package typeset

// Enum used to identify the type of notification
const (
	NOTIFICATION_BINANCE_CONNECT = iota
	NOTIFICATION_INTEGRATION_START
	NOTIFICATION_INTEGRATION_FINISH
	NOTIFICATION_PAY_WITHDRAW
	NOTIFICATION_PAY_DEPOSIT
	NOTIFICATION_SWAP
	NOTIFICATION_VAULT
	NOTIFICATION_WALLET_CONNECT
)
